# Generated by Django 5.0.7 on 2024-11-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_category_id_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summer_or_winter",
            field=models.CharField(
                choices=[("winter", "Winter")], max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent_category_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
