# Generated by Django 5.0.7 on 2024-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_summer_or_winter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summer_or_winter",
            field=models.CharField(
                choices=[("summer", "صيفي"), ("winter", "شتوي")],
                max_length=20,
                null=True,
            ),
        ),
    ]
