# Generated by Django 5.0.7 on 2024-11-10 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_summer_or_winter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True, default=datetime.datetime.today, null=True
            ),
        ),
    ]
