# Generated by Django 5.0.7 on 2024-11-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="product_variation",
            name="sku",
        ),
    ]
