# Generated by Django 5.1.2 on 2024-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_is_on_sale_product_sale_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent_category_id",
        ),
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
