# Generated by Django 5.1.2 on 2024-12-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
